language: java
# use Java 8
#jdk:
#  - oraclejdk
sudo: required
services:
  - docker
before_Script:
 # cd src/docker/
  - docker-compose -f docker/dev/docker-compose.yml up 
script:
  - docker-compose build
after_success:
  - mvn --file ./src/pom.xml clean test -P test-consumer,test-business
