language: java
# use Java 8
#jdk:
#  - oraclejdk
sudo: required
services:
  - docker
before_script:
  - docker-compose -f ./src/docker/dev/docker-compose.yml up --build
script: mvn --file ./src/pom.xml clean test -P test-consumer,test-business
