language: java
# use Java 8
#jdk:
#  - oraclejdk
sudo: required
services:
  - docker
before_script:
 # cd src/docker/
  - docker-compose -f docker/dev/docker-compose.yml up -d
#script:
#  - docker-compose build
script:
  - mvn --file ./src/pom.xml clean test -P test-consumer,test-business
