language: java
# use Java 8
#jdk:
#  - oraclejdk
sudo: required
services:
  - docker
#services:
#  - postgresql
#test:
#  adapter: postgresql
#  database: db_myerp
 # username: postgres
 # password: myerp
before_script:
  - docker-compose --f ./src/docker/dev/docker-compose.yml up
script: mvn --file ./src/pom.xml clean test -P test-consumer,test-business

