language: java
# use Java 8
jdk:
  - oraclejdk8
sudo: false
services:
  - docker
#install: pip install codecov
#addons:
#  postgresql: "10.4"
#services:
#  - postgresql
#test:
#  adapter: postgresql
#  database: db_myerp
#  username: postgres
 # password: myerp
before_script:
  - docker-compose -f docker/dev/docker-compose.yml up -d
script: 
  - mvn --file ./src/pom.xml clean package -P test-consumer,test-business
  - mvn --file ./src/pom.xml cobertura:cobertura -P test-consumer,test-business
  - docker-compose -f docker/dev/docker-compose.yml ps
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
