language: java
# use Java 8
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
#services:
#  - postgresql
#test:
#  adapter: postgresql
#  database: db_myerp
#  username: postgres
 # password: myerp
before_install:
  - docker-compose -f docker/dev/docker-compose.yml up -d
script: mvn --file ./src/pom.xml clean package -P test-consumer,test-business
notifications:
  email: false
