language: java
# use Java 8
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
#addons:
#  postgresql: "10.4"
#services:
#  - postgresql
#test:
#  adapter: postgresql
#  database: db_myerp
#  username: postgres
 # password: myerp
#before_install:
 # - docker-compose -f docker/dev/docker-compose.yml up --build
script: 
  - docker-compose -f docker/dev/docker-compose.yml up --build
after_success:
  - mvn --file ./src/pom.xml clean package -P test-consumer,test-business
  - docker-compose -f docker/dev/docker-compose.yml ps
notifications:
  email: false
