language: java
# use Java 8
jdk:
  - oraclejdk8
 #sudo: required
services:
  - postgresql
#services:
#  - postgresql
test:
  adapter: postgresql
  database: vkckkmjl
  username: vkckkmjl
 # password: myerp
#before_script:
 # - "psql -c 'create database db_myerp;' -U postgres"
script: mvn --file ./src/pom.xml package -P test-consumer,test-business
notifications:
  email: false
